---
server:
  port: 8082

spring:
  application:
    name: pong-service

eureka:
  instance:
    nonSecurePort: 8082
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

reply:
  message: Pong local